return PlaceObj('ModDef', {
	'title', "Global Birth Control Policies",
	'description', "This mod add a global birth control policy, ontop of the local dome policies. You can set how many overall children you want via mod options under options.\n\nPersonally, being able to set limit to children globally and use shuttle hub to deal with transportation needs are an ideal way to reduce birth control micro because you can decide the said limit base on your situation like population, housing or educations.\n\nDo note that this does not override local dome policies so if you forbid birth in all domes but set global to 100, no child will be born due to local policy.",
	'image', "preview.jpg",
	'last_changes', "Updated algorithm, making it less prone to game load bug. The mod is also now enabled by default.",
	'id', "IiJwcB",
	'pops_desktop_uuid', "5007974e-6cb6-4120-a057-f28dfbf5d8f9",
	'pops_any_uuid', "624ae7b8-5105-4035-b4b1-1e160a9b273c",
	'author', "unknown",
	'version_major', 1,
	'version_minor', 1,
	'version', 33,
	'lua_revision', 1009413,
	'saved_with_revision', 1010784,
	'code', {
		"Code/GlobalBirthControlPolicies.lua",
	},
	'has_options', true,
	'saved', 1642584209,
	'TagGameplay', true,
})
